name: "Testing Hello World" 
on:
  workflow_dispatch
jobs:
  hello: 
    runs-on:  ubuntu-latest

    steps:
      - run: echo "Hello, World!"
      - run: echo "Triggered by ${{ github.property.actor }}
